version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "superSecretPassword"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  api:
    build: .
    image: gopportunities-api:latest
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release